#ifndef _MERRY_GRAVES_CONSTANTS_
#define _MERRY_GRAVES_CONSTANTS_

typedef enum mgreq_t mgreq_t; // Merry Graves Request

enum mgreq_t {
  SHUT_DOWN,
  TRY_LOADING_NEW_PAGE_INST,
  TRY_LOADING_NEW_PAGE_DATA,
  PROBLEM_ENCOUNTERED,
  PROGRAM_REQUEST,
};

// PROGRAM REQUESTS
enum {
  NEW_THREAD,
  ADD_A_NEW_DATA_MEMORY_PAGE,
  SAVE_STATE,
  DELETE_STATE,
  JMP_STATE,
  SWITCH_STATE,
  WILD_RESTORE,
};

// PROGRAM REQUESTS RESULT
enum {
  REQUEST_SERVED,
  REQUEST_FAILED,
  FAILED_TO_ADD_CORE,
  FAILED_TO_BOOT_CORE,
  FAILED_TO_ADD_DATA_MEMORY_PAGE,
};

#endif
