#ifndef _MERRY_GRAVES_CONSTANTS_
#define _MERRY_GRAVES_CONSTANTS_

typedef enum mgreq_t mgreq_t; // Merry Graves Request

enum mgreq_t {
  SHUT_DOWN,
  TRY_LOADING_NEW_PAGE_INST,
  TRY_LOADING_NEW_PAGE_DATA,
  PROBLEM_ENCOUNTERED,
  PROGRAM_REQUEST,
};

// PROGRAM REQUESTS
enum {
  NEW_THREAD,
  ADD_A_NEW_DATA_MEMORY_PAGE,
  NEW_GROUP,
  SAVE_STATE,
  DELETE_STATE,
  JMP_STATE,
  SWITCH_STATE,
  WILD_RESTORE,
  BESTOW_PRIVILEDGE,
  DO_NOT_DISTURB,
  IGNORE_PAUSE,
  WILD_REQUEST,
  PAUSE,
  UNPAUSE,
  GRANT_PERMISSION,
  IS_CORE_DEAD,
  IS_PARENT_ALIVE,
  GET_CID,
  GET_UID,
  GET_GROUP,
  KILL_CORE,
  IS_CHILD,
  CHANGE_PARENT,
  CHANGE_CHILD_PARENT,
  GIVEUP_PRIVILEDGE,
  PURGE_WREQUESTS,
};

// PROGRAM REQUESTS RESULT
enum {
  REQUEST_SERVED,
  REQUEST_FAILED,
  FAILED_TO_ADD_CORE,
  FAILED_TO_BOOT_CORE,
  FAILED_TO_ADD_DATA_MEMORY_PAGE,
  NOT_PRIVILEDGED,
  CANNOT_PAUSE,
  WRQ_FULL,
  CORE_DEAD,
  CORE_ALIVE,
  HAS_NO_PARENT, // meaning it itself is a parent
  YES,
  NO,
  NEW_PARENT_NOT_PRIVILEDGED,
  WILD_REQUEST_HDLR_NOT_SET,
  INVALID_CORE_ID,
};

#endif
