#ifndef _MERRY_TOKEN_TYPES_
#define _MERRY_TOKEN_TYPES_

typedef enum token_t token_t;

enum token_t {
  TOK_EOF,
  TOK_ERR,
  TOK_TMP,
  TOK_OPEN_PAREN,
  TOK_CLOSE_PAREN,
  TOK_NUM_INT,
  TOK_NUM_FLOAT,
  TOK_NUM_BINARY,
  TOK_NUM_OCTAL,
  TOK_NUM_HEX,
  TOK_FLOAT,
  TOK_PLUS,
  TOK_MINUS,
  TOK_MUL,
  TOK_DIV,
  TOK_MODULO,
  TOK_GREATER,
  TOK_SMALLER,
  TOK_GREATER_EQUAL,
  TOK_SMALLER_EQUAL,
  TOK_IS_EQUAL,
  TOK_NOT_EQUAL,
  TOK_AND,
  TOK_OR,
  TOK_BITWISE_NOT,
  TOK_BITWISE_AND,
  TOK_BITWISE_OR,
  TOK_BITWISE_XOR,
  TOK_IDENTIFIER,
  TOK_NON_EXPRESSION,
};

#endif
