# This will be the comment(don't put one at the lines where the data is provided)
# This configuration file is not a configuration in a real sense hence its name may change as we go
# The main purpose of this file is to store the names of cores and paths to their executables
# Eg: core_name = path_to_exe
# paths should be absolute(ignore what is here)

test_core = build/test_core
